# Generated by Django 3.1.5 on 2021-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='mehsulun adi')),
                ('price', models.IntegerField(verbose_name='mehsulun qiymeti')),
                ('description', models.TextField(verbose_name='mehsulun xususiyyetleri')),
                ('stock_status', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='Əlavə edilmə tarixi')),
                ('category', models.ManyToManyField(to='categories.ProductCategory', verbose_name='kategoriya')),
                ('filter_category', models.ManyToManyField(to='categories.FilterCategory', verbose_name='filter')),
            ],
        ),
    ]
