# Generated by Django 3.1.5 on 2021-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.ProductCategory', verbose_name='kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_category',
            field=models.ManyToManyField(blank=True, to='categories.FilterCategory', verbose_name='filter'),
        ),
    ]
