# Generated by Django 3.1.5 on 2021-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('products', '0002_auto_20210323_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.ProductImage'),
        ),
    ]
