# Generated by Django 3.1.5 on 2021-03-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('images', '0001_initial'),
        ('products', '0003_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.productcategory', verbose_name='kategoriya'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='filter_category',
        ),
        migrations.AddField(
            model_name='product',
            name='filter_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.filtercategory', verbose_name='filter'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.productimage'),
        ),
    ]
