# Generated by Django 3.1.5 on 2021-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0004_auto_20210325_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.ProductCategory', verbose_name='kategoriya'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='filter_category',
        ),
        migrations.AddField(
            model_name='product',
            name='filter_category',
            field=models.ManyToManyField(blank=True, to='categories.FilterCategory', verbose_name='filter'),
        ),
    ]
