# Generated by Django 3.1.5 on 2021-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_productimage_product'),
        ('products', '0005_auto_20210325_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.ProductImage'),
        ),
    ]
