# Generated by Django 3.1.5 on 2021-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRigth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10)),
                ('context', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('email_3', models.EmailField(blank=True, max_length=254)),
                ('email_4', models.EmailField(blank=True, max_length=254)),
                ('email_5', models.EmailField(blank=True, max_length=254)),
                ('email_6', models.EmailField(blank=True, max_length=254)),
                ('phone_number_1', models.CharField(max_length=200)),
                ('phone_number_2', models.CharField(blank=True, max_length=200)),
                ('phone_number_3', models.CharField(blank=True, max_length=200)),
                ('phone_number_4', models.CharField(blank=True, max_length=200)),
                ('phone_number_5', models.CharField(blank=True, max_length=200)),
                ('phone_number_6', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_d_from', models.CharField(max_length=100)),
                ('duration_d_to', models.CharField(max_length=100)),
                ('duration_t_from', models.CharField(max_length=100)),
                ('duration_t_to', models.CharField(max_length=100)),
                ('saturday', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
