# Generated by Django 3.1.5 on 2021-03-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingduration',
            old_name='saturday',
            new_name='saturday_from',
        ),
        migrations.AddField(
            model_name='workingduration',
            name='saturday_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
