# Generated by Django 3.1.5 on 2021-03-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
