  nginx:
    image: nginx:latest
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../static:/var/www/backend/static_files
      - ../media:/var/www/backend/media

