# Generated by Django 3.1.5 on 2021-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_images'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order_user',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='Məhsullar'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ordered_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Sifarişin edilmə tarixi'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
